# -*- coding: utf-8 -*-
"""lv3_이중우선순위큐.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ct56AbV-JNTrEHbpndnaXw03BlpRawU_
"""

import heapq

def solution(operations):
    heap = []
    for i in operations:
        k = i.split()
        if k[0] == 'I':   # I인 경우 큐에 숫자 삽입
            heapq.heappush(heap, int(k[1]))
        else:
            if not heap:  # 삭제할 데이터가 없는 경우
                continue
            if k[1] == '-1':   # D -1인 경우 최솟값 삭제
                heapq.heappop(heap)
            else:   # D 1인 경우 최대값 삭제
                heap = heapq.nlargest(len(heap), heap)[1:]
                heapq.heapify(heap)      
                
    if not heap:   # 큐가 비어있으면 [0,0]
        return [0, 0]
    else:   # 비어있지 않으면 [최댓값, 최솟값]
        return [max(heap), min(heap)]

print(solution(["I 16", "I -5643", "D -1", "D 1", "D 1", "I 123", "D -1"]))
print(solution(["I -45", "I 653", "D 1", "I -642", "I 45", "I 97", "D 1", "D -1", "I 333"]))