# -*- coding: utf-8 -*-
"""lv2_구명보트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t46SHWnMw1nVsl13Cfc-mJmNOaqcUHTq
"""

# 구명보트

def solution(people, limit):
    i = answer = 0
    j = len(people) - 1
    people.sort()   # 오름차순 정렬 (가벼운사람 -> 무거운사람)
    
    while i <= j:
        # 몸무게가 가장 작은사람+큰사람이 제한 무게보다 작으면 둘 다 태움
        if people[i] + people[j] <= limit:
            i += 1
        # 제한무게를 넘어가면 가장 무거운 사람을 태움
        j -= 1
        answer += 1    # 사용된 구명보트 개수
        
    return answer

print(solution([70, 50, 80, 50],100))
print(solution([70, 80, 50],100))