# -*- coding: utf-8 -*-
"""lv2_더 맵게.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQ08qlgPh0eu0kjKglI8c3OPPWc-B-De
"""

import heapq
def solution(scoville, K):
    heapq.heapify(scoville)
    count=0
    
    # 스코빌 지수 계산
    while scoville[0] < K:
        # 모든 스코빌 지수를 K이상으로 만들 수 없는 경우
        if len(scoville) == 1: 
            return -1
        
        a = heapq.heappop(scoville) # 제일 작은 스코빌 지수
        b = heapq.heappop(scoville) # 2번째로 작은 스코빌 지수
        heapq.heappush(scoville, a+b*2) # 새로운 음식 스코빌 지수 추가
        count += 1   # 섞은 횟수
        
    return count

print(solution([1, 2, 3, 9, 10, 12], 7))