# -*- coding: utf-8 -*-
"""lv2_올바른 괄호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E0jFcFb_pZV-GJYnIBkaUusVDFy6RCWY
"""

def solution(s):
    answer = []

    for i in s :
        if i == '(' :
            answer.append(i)
        else :
            if answer == [] :
                return False
            else :
                answer.pop()
    
    if answer == [] :
        return True
    else :
        return False

print(solution("()()"))
print(solution("(())()"))
print(solution(")()("))
print(solution("(()("))