# -*- coding: utf-8 -*-
"""lv2_모음사전.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5XOVScmZZFPoAQL1iE5yjGkCSRC9qoo
"""

from itertools import product

def solution(word):
    alpha = ['A', 'E', 'I', 'O', 'U']   # 사전으로 생성되는 알파벳 모음
    answer = []   # 길이 5 이하의 모든 단어를 사전식으로 수록

    # 5개의 단어로 나올 수 있는 모든 경우의 수 저장 (중복순열)
    for i in range(1,6):
        answer += list(map(''.join, product(alpha,repeat = i)))

    answer.sort()   # 사전순으로 정렬

    return answer.index(word)+1   # 찾는 문자의 인덱스+1값 리턴

print(solution("AAAAE"))
print(solution("AAAE"))
print(solution("I"))
print(solution("EIO"))