# -*- coding: utf-8 -*-
"""lv1_프린터.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HSDWguvNWl2x884gt4HeyBRxnAxSBlWS
"""


priorities1 = [2, 1, 3, 2]   # location 2
priorities2 = [1, 1, 9, 1, 1, 1]   # location 0

def solution(priorities, location):
    list = []
    answer = 0

    while True :
        for i in range(len(priorities)) :
            if priorities[i] == max(priorities) :
                priorities[i] = 0
                answer += 1
                if i == location :
                    return answer

print(solution(priorities1, 2))
print(solution(priorities2, 0))
