# -*- coding: utf-8 -*-
"""lv2_카펫.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16yNy04M3hQNLT5TLi8zwkAHFvAm9NwWJ
"""

def solution(brown, yellow):
    for i in range(1,int(yellow**0.5+1)):
        if yellow % i == 0:
            a, b = i, yellow//i   # a = 가로, b = 세로
            if brown == a*2 + b*2 + 4:   # 갈색 격자 수 = (노랑 가로 길이*2)+(노랑 세로 길이*2)+4
                return [max(a,b)+2, min(a,b)+2]   # 가로, 세로 출력

print(solution(10,2))
print(solution(8,1))
print(solution(24,24))