# -*- coding: utf-8 -*-
"""lv1_서울에서 김서방 찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDkyj6YlDmNJSn8LIk7kZVfy_6nnW3Bt
"""

def solution(seoul):
    answer = seoul.index('Kim')
    return '김서방은 {}에 있다'.format(answer)

print(solution(["Jane", "Kim"]))