# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkWf4v5TTN0VqJIx9ptwjRBPn1DcHdl5
"""

participant = ["mislav", "stanko", "mislav", "ana"]
completion = ["stanko", "ana", "mislav"]

def solution(participant, completion):
    for i in completion :
        participant.remove(i)

    return participant[0]

print(solution(participant,completion))