# -*- coding: utf-8 -*-
"""lv1_최소직사각형.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tjmVOH7xJdmUh57WSrXxgGDdiWe6N9oO
"""

def solution(sizes):
    w, h = [], []
    for i,j in sizes:
        if i<j:
            i,j = j,i
        w.append(i)
        h.append(j)

    return max(w) * max(h)

print(solution([[60, 50], [30, 70], [60, 30], [80, 40]]))
print(solution([[10, 7], [12, 3], [8, 15], [14, 7], [5, 15]]))
print(solution([[14, 4], [19, 6], [6, 16], [18, 7], [7, 11]]))