# -*- coding: utf-8 -*-
"""lv1_제일 작은 수 제거하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwVHxF0wR_7LYcKNUOTIrky68jjxOReq
"""

def solution(arr):
    arr.remove(min(arr))
    
    if arr == [] :
        return [-1]
    
    return arr

print(solution([4,3,2,1]))
print(solution([10]))