# -*- coding: utf-8 -*-
"""lv1_소수 찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6STVhWbwEOigmedghySErWDTKB7ytfI
"""

def solution(n):
    answer = 0
    for i in range(2, n+1):
        check = 1
        for j in range(2,int(i**0.5)+1):
            if i % j == 0:
                check = 0
                break
                
        if check: 
            answer +=1
        
    return answer

print(solution(10))
print(solution(5))