# -*- coding: utf-8 -*-
"""lv1_두 정수 사이의 합.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QVfDSeh8Pf9oZ9HptJ4NhvXolOn5XZQ
"""

# 풀이
def solution(a, b):
    answer = 0
    if a == b :
        return a
    elif a < b :
        for i in range(a,b+1) :
            answer += i
        return answer
    else :
        for i in range(b,a+1) :
            answer += i
        return answer
    
print(solution(3,5))
print(solution(3,3))
print(solution(5,3))

# 최적 코드

def adder(a, b):
    return sum(range(min(a,b), max(a,b) + 1))