# -*- coding: utf-8 -*-
"""lv1_두 개 뽑아서 더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19lGecGDnPNLsq-aJhGIouCrJecESLlz2
"""

# 내 풀이

from itertools import combinations

def solution(numbers):
    answer = []
    for i in list(combinations(numbers, 2)):   # 2개의 원소로 나올 수 있는 모든 조합
        answer.append(sum(i))
    return sorted(set(answer))     # sorted() -> 리스트로 반환

print(solution([2,1,3,4,1]))
print(solution([5,0,2,7]))