# -*- coding: utf-8 -*-
"""lv1_핸드폰 번호 가리기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DPmNF6HUC-_lQMKrFwFp6MxQ4vhPzM46
"""

def solution(phone_number):
    return '*'* (len(phone_number)-4) + phone_number[-4:]

print(solution("01033334444"	))
print(solution("027778888"))