# -*- coding: utf-8 -*-
"""lv1_폰켓몬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GMJfvqzmdHR5N3AtkIP9XPzb0QLcGPmz
"""

nums = [3,3,3,2,2,2]

def solution(nums):
    new_nums = []
    for i in nums :
        if i not in new_nums :
            new_nums.append(i)     # 중복제거
    
    if len(nums)/2 <= len(new_nums) :   # 크기비교
        return len(nums)/2
    else :
        return len(new_nums)

'''
간단 풀이

def solution(nums):
    return min(len(nums)/2, len(set(nums)))
'''

print(solution(nums))