# -*- coding: utf-8 -*-
"""lv1_문자열을 정수로 바꾸기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18MLu_MrXzkCH1N_Mu3GDSqUOW17MrGP-
"""

def solution(s):
    answer = int(s)
    return answer


print('1234')
print('-1234')