# -*- coding: utf-8 -*-
"""lv1_없는 숫자 더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJ50yp4RSUGAAWSHSYpG_4YdndjRB4KJ
"""

def solution(numbers):
    answer = 0
    for i in range(10) :
        if i not in numbers :
            answer += i
    return answer

print(solution([1,2,3,4,6,7,8,0]))
print(solution([5,8,4,0,6,7,9]))

'''
최적 코드

def solution(numbers):
    return 45 - sum(numbers)
'''