# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XC62PMyJPA-w-h6DieOaKj7JtJJpyhPK
"""

def solution(x, n):
    answer = []
    i=1
    
    while len(answer) < n :
        answer.append(i*x)
        i += 1
    return answer

print(solution(2,5))
print(solution(4,3))
print(solution(-4,2))