# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udu6Owe7U2b16y9SzAkF5dmvev2AtRts
"""

a, b = map(int, input().strip().split(' '))
answer = ('*'*a +'\n') * b
print(answer)