# -*- coding: utf-8 -*-
"""lv1_자연수 뒤집어 배열로 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmLiyrGZE6-f-Zb5mBmMbLJ7pWaLoXEq
"""

n = 12345

def solution(n):
    answer = list(map(int, str(n)))
    answer.reverse()
    
    return answer

print(solution(n))