# -*- coding: utf-8 -*-
"""lv1_정수 제곱근 판별.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gqSYe3G_4znOyiLIXOholypCAiA7q0Lh
"""

def solution(n):
    if (n**(1/2)) % 1 == 0:
        return (n**(1/2)+1)**2
    else :
        return -1
  
print(solution(121))
print(solution(3))