# -*- coding: utf-8 -*-
"""lv1_같은 숫자는 싫어.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hRuoiqJl1ImYHdchk8103VfolvNl3IZ0
"""

arr = [1,1,3,3,0,1,1]
arr2 = [4,4,4,3,3]

def solution(arr):
    answer = [(arr[0])]
    
    for i in range(1, len(arr)) :
        if  arr[i] != arr[i-1] :
            answer.append(arr[i])
    
    return answer


print(solution(arr))
print(solution(arr2))