# -*- coding: utf-8 -*-
"""lv1_나머지가 1이 되는 수 찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VVD2nK9mEuS_L6nsEA0jOajZNfou7GuO
"""

def solution(n):
    for i in range(1,n) :
        if n % i == 1 :
            return i

print(solution(10))
print(solution(12))