# -*- coding: utf-8 -*-
"""lv1_문자열 내 p와 y의 개수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12u0I_hHi8cXeX7TJDeOS90n9SsTeQoRO
"""

def solution(s):
    
    if s.count('p')+s.count('P') == s.count('y')+s.count('Y') :
        return True
    
    return False

print(solution("pPoooyY"))
print(solution("Pyy"))