# -*- coding: utf-8 -*-
"""lv1_콜라츠 추측.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pk6kWOIABkbeuCXPrcK08WDpZPzv18XL
"""

def solution(num):
    count = 0
    
    if num == 1:
        return 0
    
    while num != 1:
        if count == 500 :
            return -1
        
        if num % 2 == 0 :
            num /= 2
        else :
            num =  3 * num + 1
        count += 1
    return count

print(solution(6))
print(solution(16))
print(solution(626331))