# -*- coding: utf-8 -*-
"""lv1_실패율.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux4JWhECrFr9y6F23mfQCWOcWSw10fUd
"""

def solution(N, stages):
    answer = {}
    length = len(stages)

    for i in range(1, N+1):
        if length == 0:      # 스테이지에 도달한 플레이어가 0명일 때
            answer[i] = 0    # 실패율 0
        else :     # 스테이지에 도달한 플레이어가 존재할 때
            answer[i] = (stages.count(i)/length)      # 실패율을 계산하여 딕셔너리로 저장
            length -= stages.count(i)     # 다음 스테이지에 도달하는 플레이어 수 계산

        # 내림차순 정렬
    return sorted(answer, key=lambda x : answer[x], reverse=True)

print(solution(5, 	[2, 1, 2, 6, 2, 4, 3, 3]))
print(solution(4, 	[4,4,4,4,4]))
print(solution(5,[2, 2, 2, 2, 2, 2, 2, 2]))