# -*- coding: utf-8 -*-
"""lv1_수박수박수박수박수박수?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c2uTFu-1rHsxGsAaZcBZ0JwXWkbgUBz3
"""

def solution(n):
    if n % 2 == 0:
        return '수박' * (n//2)
    else :
        return '수박' * (n//2) + '수'

print(solution(3))
print(solution(4))