# -*- coding: utf-8 -*-
"""lv1_푸드 파이트 대회.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQ72LYz2qSMTgsFBX4gZRMJviPzZXJaN
"""

def solution(food):
    answer = ''

    for idx, i in enumerate(food):
        if i != 1:    # 음식의 양이 1이면 대회에 사용할 수 없으므로 제외
            answer += str(idx) * (i // 2)    # 선수 한명이 먹어야 하는 음식의 배치
            
    return answer + '0' + answer[::-1]

print(solution([1, 3, 4, 6]))
print(solution([1, 7, 1, 2]))