# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qikzfpG7gUPE002vSzQmZmxCbZAbqnSv
"""

def solution(n):
    List = list(map(int,str(n)))
    return sum(List)


print(solution(123))
print(solution(987))