# -*- coding: utf-8 -*-
"""lv1_하샤드 수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RhXqWCfaFR7XsvY-RF_WCqY1OQljAG_
"""

def solution(x):
    num = sum( list(map(int, str(x))) )
    
    if x % num == 0 :
        return True
    
    return False


print(solution(10))
print(solution(11))
print(solution(12))