# -*- coding: utf-8 -*-
"""lv1_문자열 내 마음대로 정렬하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11pvwErUgYS3FTTpgZxapjhNO5dqePU-C
"""

# 첫번째 풀이

def solution(strings, n):
    answer, alpha_list = [], []

    # 주어진 리스트 사전순 정렬
    strings.sort()
    re_move = strings

    # 각 문자열의 인덱스 n번째 글자를 저장하여 정렬
    for i in strings:
        alpha_list.append(i[n])
    alpha_list.sort()
    
    # n번째 글자를 비교하여 일치하면 answer에 저장 & 저장된 글자는 제거
    for i in alpha_list:
        for j in strings:
            if i == j[n]:
                answer.append(j)
                re_move.remove(j)
                break
    
    return answer

print(solution(["sun", "bed", "car"], 1))
print(solution(["abce", "abcd", "cdx"], 2))
print(solution(["aea", "ba", "ce", "aee"], 1))

# 두번째 풀이 - sorted() 함수의 매개변수 key 사용

# key 매개변수의 값 : 단일 인자를 취하며 정렬 목적으로 사용할 키를 반환
#                     람다 표현식 사용

def solution(strings, n):
    
    return sorted(sorted(strings), key=lambda x : x[n])

print(solution(["sun", "bed", "car"], 1))
print(solution(["abce", "abcd", "cdx"], 2))
print(solution(["aea", "ba", "ce", "aee"], 1))