# -*- coding: utf-8 -*-
"""Lv1_약수의 합.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svSoI9s2JMtA7FQLAjp6LbunJQ4GsuwK
"""

def solution(n):
    answer = 0
    for i in range(1,n+1) :
        if n % i == 0 :
            answer += i
    return answer

print(solution(12))
print(solution(5))