# -*- coding: utf-8 -*-
"""lv1_이상한 문자 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tby6mEuVkxYGG13ctbfd1MzLE1nwXGhy
"""

def solution(s):
    s = s.split(' ')
    answer = ''
    for i in s:
        for idx, word in enumerate(i):
            if idx % 2 == 0:
                answer += word.upper()
            else:
                answer += word.lower()
        answer += ' '

    return answer[:-1]

print(solution("try hello world"))