# -*- coding: utf-8 -*-
"""github 다운로드 전용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux4JWhECrFr9y6F23mfQCWOcWSw10fUd
"""

def solution(s):
    alpha = {"zero":"0", "one":"1", "two":"2", "three":"3", "four":"4", "five":"5", "six":"6", "seven":"7", "eight":"8", "nine":"9"}
    for i in alpha:
        s = s.replace(i, alpha[i])
    return int(s)

print(solution("one4seveneight"))
print(solution("23four5six7"))
print(solution("2three45sixseven"))
print(solution("123"))