# -*- coding: utf-8 -*-
"""lv1_콜라 문제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wyYe8E8ZRMEXYNfK3H4vZbKHfsydFN2x
"""

def solution(a, b, n):
    get = remain = 0  # get = 새로운 병, remain = 교환하지 못한 빈병

    # 교환 불가능할 때까지 반복
    while a <= n:
        remain = n % a    # 교환 못한 병의 수
        n = n // a * b    # 교환한 병의 수
        get += n          # 교환한 병의 누적수
        n += remain       # 교환 가능한 병의 수

    return get

print(solution(2,1,20))
print(solution(3,1,20))
print(solution(3,2,20))