# -*- coding: utf-8 -*-
"""lv1_로또의 최고 순위와 최저 순위.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux4JWhECrFr9y6F23mfQCWOcWSw10fUd
"""

def solution(lottos, win_nums):
    low = high = 0

    cnt = lottos.count(0)   # 알아볼 수 없는 번호의 개수
    for i in win_nums:
        if i in lottos:
            low +=1         # 번호가 일치하면 +1

    answer = [7 - (low + cnt), 7 - low]    # 최대, 최저 순위 저장

    for idx, i in enumerate(answer):   # 순위가 5 아래인 경우 낙첨
        if i > 5:
            answer[idx] = 6

    return answer


print(solution([44, 1, 0, 0, 31, 25],	[31, 10, 45, 1, 6, 19]))
print(solution([0, 0, 0, 0, 0, 0], 	[38, 19, 20, 40, 15, 25]))
print(solution([45, 4, 35, 20, 3, 9], [20, 9, 3, 45, 4, 35]))