# -*- coding: utf-8 -*-
"""lv1_정수 내림차순으로 배치하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDq3vqAkXyfIltBP6pTwMPLe3IRCnx2P
"""

def solution(n):
    answer = list(str(n))
    answer.sort(reverse = True)
    answer = int(''.join(answer))
    
    return answer

print(solution(118372))