# -*- coding: utf-8 -*-
"""lv1_음양 더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMwx1gnvouBugQtAM2vtSj8LecO4thqS
"""

absolutes1 = [4,7,12]
absolutes2 = [1,2,3]
signs1 = [1,0,1]
signs2 = [0,0,1]

def solution(absolutes, signs):
    answer = 0
    for i in range(len(signs)) :
        if signs[i] :
            answer += absolutes[i]
        else :
            answer -= absolutes[i]
    return answer

print(solution(absolutes1,signs1))
print(solution(absolutes2,signs2))