# -*- coding: utf-8 -*-
"""Lv1_평균구하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Akx3N-3ET7MfnlYQToxR5Qly_dZJLWbc
"""

a = [1,2,3,4]
b = [5, 5]

def solution(arr):
    answer = 0
    for i in arr :
        answer += i
    return answer / len(arr)

print(solution(a))
print(solution(b))