# -*- coding: utf-8 -*-
"""lv1_[1차] 비밀지도.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14zuEGDii-8bDQWH0lG8ESFU7VzyJt0m1
"""

def solution(n, arr1, arr2):
    answer = []
    for i in range(n):
        bin1 = bin(arr1[i])[2:]
        bin2 = bin(arr2[i])[2:]

        if len(bin1) < n:
            bin1 = '0'*(n-len(bin1)) + bin1
        if len(bin2) < n:
            bin2 = '0'*(n-len(bin2)) + bin2

        result = ''
        for j,k in zip(bin1, bin2):
            if j == '0' and k == '0':
                result += ' '
            else:
                result += '#'

        answer.append(result)

    return answer

print(solution(5, [9, 20, 28, 18, 11], 	[30, 1, 21, 17, 28]))
#print(solution(6, [46, 33, 33 ,22, 31, 50], [46, 33, 33 ,22, 31, 50]))