# -*- coding: utf-8 -*-
"""Lv1_짝수와 홀수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vuymn-coVggG7ADPEvs5MQtAHPzmaDcT
"""

def solution(num):
    if num % 2 == 0 :
        return "Even"
    else :
        return "Odd"

print(solution(3))
print(solution(4))